#!/bin/bash -x

REPOSITORY=$1
NAME=$2
REFSPEC=$3
DIRECTORY=$4
SSH_KEY=$5

echo $0

if [ "x$DIRECTORY" = "x" ];then
    DIRECTORY=/tmp
fi

cd "$DIRECTORY"

if [ "x$SSH_KEY" != "x" ];then
    echo "Private repository. using separate ssh key $SSH_KEY"
    echo "exec /usr/bin/ssh -o StrictHostKeyChecking=no -i "$SSH_KEY" \"\$@\"" > ./gitsh
    chmod +x ./gitsh
    export GIT_SSH="$PWD/gitsh"
fi


if [ ! -e "$NAME" ]; then
    echo "Cloning '$REPOSITORY' to '$NAME'"
    git clone "$REPOSITORY" "$NAME"
    cd "$NAME"
    git submodule init
    git submodule update
    cd ..
fi

if [ ! -d "$NAME" ]; then
    echo "Cannot create git repository"
    exit 1
fi

cd "$NAME"

if [ ! -e .git/config ]
then
    echo "Configuring Git"
    git init
    git add app config lib public script config.ru Gemfile Gemfile.lock main_app.ru Procfile Rakefile .gitignore
    git commit -a -m update
else
    echo "Git is already configured"
fi

echo "Before Pull:"
git log | head -3
git stash
git pull
git submodule update
echo "After:"
git log | head -3
echo "Checkout $REFSPEC"
git checkout "$REFSPEC"
git log | head -3
echo "Before Final pull"
git pull
echo "After Final pull"
git log | head -3

